baseURL = "https://example.com/"
title = "Spectrum AI"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.pl]
    languageName = "Polski"
    weight = 2
    contentDir = "content/pl"

  [languages.fr]
    languageName = "Français"
    weight = 3
    contentDir = "content/fr"

